stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - params.yaml:
      - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  features_engineering:
    cmd: python src/features_engineering.py
    deps:
    - data/interim
    - src/features_engineering.py
    params:
    - params.yaml:
      - feature_engineering.max_features
    outs:
    - data/processed
    - models/vectorizer.pkl

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/processed
    - models
    - src/model/model_evaluation.py
    outs:
    - reports
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step